export const GET_GAME_SIMULATION = "GET_GAME_SIMULATION";
export const GET_GAME_SIMULATION_INITIAL = "GET_GAME_SIMULATION_INITIAL";
export const GET_GAME_SIMULATION_REQUEST = "GET_GAME_SIMULATION_REQUEST";
export const GET_GAME_SIMULATION_SUCCESS = "GET_GAME_SIMULATION_SUCCESS";
export const GET_GAME_SIMULATION_ERROR = "GET_GAME_SIMULATION_ERROR";
