export const GET_GAME_DATA = "GET_GAME_DATA";
export const GET_GAME_DATA_REQUEST = "GET_GAME_DATA_REQUEST";
export const GET_GAME_DATA_SUCCESS = "GET_GAME_DATA_SUCCESS";
export const GET_GAME_DATA_ERROR = "GET_GAME_DATA_ERROR";
